### ISSUE TITLE
Lỗi khi click vào playlist trên màn hình home

### ISSUE THREAD

**Issue by trinhvanbien** [trinhvanbien/testcase_mc#11]
06-20 09:34:42.176    3783-3783/com.bluesky.musiccloudbeta E/TrackCount:﹕ 0
06-20 09:34:42.308    3783-3783/com.bluesky.musiccloudbeta E/roboguice﹕ Throwable caught during background processing
    java.lang.NullPointerException
            at com.bluesky.musiccloud.PlaylistActivity$GetDataAsyncTask.onSuccess(PlaylistActivity.java:706)
            at com.bluesky.musiccloud.PlaylistActivity$GetDataAsyncTask.onSuccess(PlaylistActivity.java:674)
            at com.bluesky.musiccloud.view.SafeAsyncTask$Task$2.call(SafeAsyncTask.java:214)
            at com.bluesky.musiccloud.view.SafeAsyncTask$Task$6.run(SafeAsyncTask.java:278)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
            at dalvik.system.VMStack.getThreadStackTrace(Native Method)
            at java.lang.Thread.getStackTrace(Thread.java:591)
            at com.bluesky.musiccloud.view.SafeAsyncTask.execute(SafeAsyncTask.java:92)
            at com.bluesky.musiccloud.PlaylistActivity$6.onLoadMoreItems(PlaylistActivity.java:382)
            at com.bluesky.musiccloud.view.PagingListView$1.onScroll(PagingListView.java:103)
            at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:1340)
            at android.widget.ListView.layoutChildren(ListView.java:1753)
            at android.widget.AbsListView.onLayout(AbsListView.java:1994)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14008)
            at android.view.ViewGroup.layout(ViewGroup.java:4373)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1892)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1711)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
            at android.view.Choreographer.doCallbacks(Choreographer.java:562)
            at android.view.Choreographer.doFrame(Choreographer.java:532)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
06-20 09:34:52.312    3783-4019/com.bluesky.musiccloudbeta E/Time to getPlaylistData﹕ 11842

**Comment by wkhoatd** [comment]
Loi nay do chua day ban moi service
