### ISSUE TITLE
Lỗi Vào Notification setting, chạy trên máy thật, vào tích vào settting chết app luôn

### ISSUE THREAD

**Issue by trinhvanbien** [trinhvanbien/testcase_mc#13]
06-22 21:06:55.528  32052-32052/com.bluesky.musiccloudbeta E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IndexOutOfBoundsException: Invalid index 3, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
            at java.util.ArrayList.get(ArrayList.java:304)
            at com.bluesky.musiccloud.NotificationSettingsActivity.savePreference(NotificationSettingsActivity.java:150)
            at com.bluesky.musiccloud.NotificationSettingsActivity.access$000(NotificationSettingsActivity.java:23)
            at com.bluesky.musiccloud.NotificationSettingsActivity$2.onCheckedChanged(NotificationSettingsActivity.java:67)
            at android.widget.CompoundButton.setChecked(CompoundButton.java:125)
            at android.widget.CompoundButton.toggle(CompoundButton.java:87)
            at android.widget.CompoundButton.performClick(CompoundButton.java:99)
            at android.view.View$PerformClick.run(View.java:14155)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:4624)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by wkhoatd** [comment]
da fix
