### ISSUE TITLE
Lỗi từ báo cáo của người dùng. phiên bản release 05/07

### ISSUE THREAD

**Issue by trinhvanbien** [trinhvanbien/testcase_mc#32]
Có 2 lỗi này, kiểm tra xem phiên bản mới đã khắc phục được chưa/

java.lang.RuntimeException: Unable to start receiver com.bluesky.musiccloud.RemoteControlReceiver: java.lang.NullPointerException
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2140)
    at android.app.ActivityThread.access$1500(ActivityThread.java:128)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4517)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.bluesky.musiccloud.RemoteControlReceiver.onReceive(RemoteControlReceiver.java:35)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2133)
    ... 10 more

java.lang.NullPointerException
    at com.bluesky.musiccloud.config.ServerConfig.getCountry(ServerConfig.java:78)
    at com.bluesky.musiccloud.GenreActivity1$2.run(GenreActivity1.java:148)
    at java.lang.Thread.run(Thread.java:856)

**Comment by wkhoatd** [comment]
Da check, chi sum serverconfig
RemoteControlReceiver.java da kiem tra lai ban moi khong co cho nao co the gay lai nullointerexeption
