### ISSUE TITLE
Khi click vào user ThinhVu trong search user bị lỗi chết app

### ISSUE THREAD

**Issue by trinhvanbien** [trinhvanbien/testcase_mc#4]
06-11 16:44:15.112    2842-3951/com.bluesky.musiccloud E/BitmapFactory﹕ Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
06-11 16:44:17.340    2842-2854/com.bluesky.musiccloud E/getWebContentgetMoreDetailOnSearchResult﹕ Message: Read timed out
06-11 16:44:21.760    2842-2842/com.bluesky.musiccloud E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity 
<img width="419" alt="screen shot 2016-06-11 at 16 47 41" src="https://cloud.githubusercontent.com/assets/4198033/15984421/45c25ec4-2ff4-11e6-8bd5-0d56f3ba9064.png">
ComponentInfo{com.bluesky.musiccloud/com.bluesky.musiccloud.ProfileActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.bluesky.musiccloud.ProfileActivity.getProfile(ProfileActivity.java:171)
            at com.bluesky.musiccloud.ProfileActivity.onCreate(ProfileActivity.java:109)
            at android.app.Activity.performCreate(Activity.java:5104)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by wkhoatd** [comment]
Đã fix.
Nguyên nhân do hàm get detailsTrackUserPlaylist get chậm.
Fix bằng cách đưa ra thông báo detail of data is loading khi click vào chi tiết
